### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by kayanouriko** [caoxiemeihao/electron-forge-vite#1]
1. 感觉作为 template 还是符合官方文档的规范比较好.  

https://github.com/caoxiemeihao/electron-forge-vite/blob/47fd449ff0a3319c1c3feefc57b49114e2d46361/vite-typescript/tmpl/main.ts#L38

根据官方文档 [#writing-a-reusable-function-to-instantiate-windows](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#writing-a-reusable-function-to-instantiate-windows) 应该使用 `whenReady` 代替吧.

https://github.com/caoxiemeihao/electron-forge-vite/blob/47fd449ff0a3319c1c3feefc57b49114e2d46361/vite-typescript/tmpl/main.ts#L49

根据官方文档 [#open-a-window-if-none-are-open-macos](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos) `activate` 事件应该也是放在 `whenReady` 里面.  

2. 第一次运行时依旧需要手动创建一个 .vite 文件夹后才不会报错.
3. 针对 `main.ts` 和 `preload.ts` 修改后, 虽然会触发编译成 js, 但并不会触发 App 的重新构建.
4. 不知道是否可以添加 pnpm 的支持.

template 使用下来确实比隔壁的简洁明了很多, 感觉作者的贡献.

**Comment by caoxiemeihao** [comment]
1. 欢迎提交 PR
2. 我这没复现这个问题。。。ts 模板已经上线，要么看看 ts 模板是否也有这个问题？
3. `main.ts` 和 `preload.ts` 修改后没有触发 App 的重新构建官方的 webpack 也不支持这个功能，到是我可以通过提供一个额外的插件实现这个效果。对此官方也没正面告诉我是不是要这个功能
4. pnpm 支持，创建一个 `.npmrc` 文件然后贴下下面的配置
```sh
# For electron-builder
# https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422
shamefully-hoist=true
```

**Comment by kayanouriko** [comment]
1. 我是初学者, 只是照着官方文档学习的时候发现的, 感觉都是代码规范的问题, 提 pr 有点厚脸皮, 还是提醒一下你来改就好了.
2. 我就是用了 ts 模板才提的, js 模板在知乎反馈过了. 用 npm 运行的, 下面是部分报错日志
```
node -v
v18.14.0

npm run start

> demo@1.0.0 start
> electron-forge start

✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [0.4s]
✔ Running generateAssets hook
(node:8948) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

An unhandled rejection has occurred inside Forge:
Error: ENOENT: no such file or directory, stat '****\Electron\demo\.vite'
```
3. 别的例如 chrome extension 的模板脚手架基本也是这样的逻辑, background.js 修改后也重载整个扩展以使代码生效. 感觉 electron 也应该这样才符合逻辑, 不然开发阶段还需要手动更新. 不过有插件实现就可以了, 希望到时候可以在文档里面提示一下或者现在可以提供一下包名_(:3.
4. 看样子还是 electron 上游的包还未支持 pnpm 的老问题, 加了这个就失去用 pnpm 的意义了, 我暂时放弃这想法了.

**Comment by caoxiemeihao** [comment]
> 看样子还是 electron 上游的包还未支持 pnpm 的老问题, 加了这个就失去用 pnpm 的意义了, 我暂时放弃这想法了

这个问题是 electron-builder 收集 node_modules 机制问题

**Comment by caoxiemeihao** [comment]
@kayanouriko Hey! 👋

1. ❌ 暂时不改动，与官方 template 保持一致。不过我会在后面先提交一个 PR 到官方的模板中使用 `whenReady()`
2. ✅ 这个问题我在 node@v14 环境下开发的，所以没碰到过 -- `electron-forge-plugin-vite@0.4.0` 已修复
3. ✅ `electron-forge-plugin-vite@0.4.0` 提供了热重启功能 -- [🔥 Hot restart](https://github.com/caoxiemeihao/electron-forge-vite/tree/main/plugin#-hot-restart)
4. ❌ pnpm 问题等 `electron-builer` 官方吧 :(
