### ISSUE TITLE
需求：支持 electron 的 utility process

### ISSUE THREAD

**Issue by flyinghail** [caoxiemeihao/electron-forge-vite#2]
electron 提供的 [utility process](https://www.electronjs.org/zh/docs/latest/api/utility-process) 用于 fork 子进程，处理一些复杂的或者是长时间的工作

这里有一个 webpack 的实现参考：https://pradyothkukkapalli.com/tech/electron-utility-process/

**Comment by flyinghail** [comment]
自己试了一下， build 可以增加 entry，所以能够很方便的把 utility-process.ts 编译出来；
目前的问题是不知道怎么能在 main.ts 里面拿到 utility-process.ts 编译后的地址；
可以直接 hard code 使用只是感觉味道不太对

**Comment by caoxiemeihao** [comment]
怎么会不知道 utility-process.ts 编译后的地址呢，因为 outDir 是在固定的地址，输出的路径是觉得可控的
是所有文件，哪怕是 main.js

**Comment by flyinghail** [comment]
是的，主要是我用的 `typescript`

`forge.config.js` 里面写加上
```javascript
build: [
	...
	{
        entry: 'src/worker.ts',
        config: 'vite.worker.config.ts',
    }
```
然后 `main.ts` 里面要写
```javascript
const child = utilityProcess.fork(path.join(__dirname, 'worker.js'))
```

我看到 `preload.js` 貌似也是这样引用的，感觉这些文件要是有类似 `MAIN_WINDOW_VITE_DEV_SERVER_URL` 这种常量来使用可能看起来会更好一些

**Comment by caoxiemeihao** [comment]
`MAIN_WINDOW_VITE_DEV_SERVER_URL` 这个也不是啥神奇的玩意儿，讲实话我甚至觉得它很没保障 😅
